{% set name = "pyCGNS" %}
{% set version = "6.3.0" %}

package:
  name: {{ name|lower }}-glob
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7f64ba14ec5c8ee1cd7a328e805d7153f7c6513161fa00e9b115740d231200f3

build:
  number: 0

outputs:
  - name: {{ name|lower }}-core
    version: {{ version }}
    script: build_core.sh  # [not win]
    script: bld_core.bat  # [win]

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}

      host:
        - python
        - pip
        - python-build
        - meson-python
        - hdf5
        - numpy
        - cython
        - pkgconfig

      run:
        - python
        - hdf5
        - numpy

    test:
      imports:
        - CGNS.MAP
        - CGNS.PAT
        - CGNS.VAL

  - name: {{ name|lower }}
    version: {{ version }}
    script: build_all.sh  # [unix]
    script: bld_all.bat  # [win]

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}

      host:
        - python
        - pip
        - python-build
        - meson-python
        - hdf5
        - numpy
        - cython
        - pkgconfig
        - qt-main
        - qtpy
        - pyside6
        - vtk

      run:
        - python
        - hdf5
        - numpy
        - qt-main
        - qtpy
        - pyside6
        - vtk

    test:
      imports:
        - CGNS.MAP
        - CGNS.PAT
        - CGNS.VAL

about:
  home: https://github.com/pyCGNS/pyCGNS
  license: LGPL-2.1-only
  license_file: LICENSE
  summary: pyCGNS provide a python interface to CGNS/SIDS datamodel for CGNS end-users and python application developpers
  doc_url: https://pycgns.github.io/
  dev_url: https://github.com/pyCGNS/pyCGNS

extra:
  recipe-maintainers:
    - MicK7
