{% set name = "pyCGNS" %}
{% set version = "6.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dd2da464ec8a149b21ca6965ee8d3c285735c985df1b1259e4d98a180d757fb9

build:
  number: 0


requirements:
  build:
    - {{ compiler('c') }}

  host:
    - python
    - pip
    - hdf5
    - numpy
    - cython
    - future
    - pkgconfig
    - qt-main         # [win]
    - qtpy       # [win]
    - pyqt       # [win]
    - vtk        # [win]

  run:
    - python
    - hdf5
    - {{ pin_compatible('numpy') }}
    - future
    - qt-main         # [win]
    - qtpy       # [win]
    - pyqt       # [win]
    - vtk        # [win]

test:
  imports:
    - CGNS.MAP
    - CGNS.PAT
    - CGNS.VAL

about:
  home: https://github.com/pyCGNS/pyCGNS
  license: LGPL-2.1-only
  license_file: LICENSE
  summary: pyCGNS provide a python interface to CGNS/SIDS datamodel for CGNS end-users and python application developpers
  doc_url: https://pycgns.github.io/
  dev_url: https://github.com/pyCGNS/pyCGNS

extra:
  recipe-maintainers:
    - MicK7
